# conda env create --file environment.yml
name: customer_segmentation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - seaborn
  - streamlit
  - scikit-learn
  - matplotlib
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.10
  - pip:
    - pyhere
